# Generated by Django 4.1 on 2022-08-30 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Password", models.CharField(max_length=12)),
                ("IsActive", models.BooleanField(default=False)),
                ("RegDate", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "master",},
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Role", models.CharField(max_length=10)),
            ],
            options={"db_table": "userrole",},
        ),
        migrations.CreateModel(
            name="Watchman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "BirthDate",
                    models.DateField(auto_created=True, default="1991-01-01"),
                ),
                (
                    "ProfileImage",
                    models.FileField(default="user.png", upload_to="profiles/"),
                ),
                ("FullName", models.CharField(blank=True, default="", max_length=25)),
                (
                    "Gender",
                    models.CharField(
                        choices=[("m", "male"), ("f", "female")], max_length=5
                    ),
                ),
                ("Mobile", models.CharField(blank=True, default="", max_length=10)),
                ("Address", models.TextField(blank=True, default="", max_length=150)),
                (
                    "Master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="house_app.master",
                    ),
                ),
            ],
            options={"db_table": "watchman",},
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Gender",
                    models.CharField(
                        choices=[("m", "male"), ("f", "female")], max_length=5
                    ),
                ),
                ("Mobile", models.CharField(blank=True, default="", max_length=10)),
                (
                    "Master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="house_app.master",
                    ),
                ),
            ],
            options={"db_table": "visitor",},
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "BirthDate",
                    models.DateField(auto_created=True, default="1991-01-01"),
                ),
                (
                    "ProfileImage",
                    models.FileField(default="user.png", upload_to="profiles/"),
                ),
                ("FullName", models.CharField(blank=True, default="", max_length=25)),
                (
                    "Gender",
                    models.CharField(
                        choices=[("m", "male"), ("f", "female")], max_length=5
                    ),
                ),
                ("Mobile", models.CharField(blank=True, default="", max_length=10)),
                (
                    "HouseNumber",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("Society", models.TextField(default="Trishul Society", max_length=50)),
                ("Pincode", models.CharField(default="380008", max_length=6)),
                ("City", models.CharField(default="Ahmedabad", max_length=25)),
                ("Country", models.CharField(default="India", max_length=25)),
                ("State", models.CharField(default="Gujarat", max_length=25)),
                (
                    "Master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="house_app.master",
                    ),
                ),
            ],
            options={"db_table": "profile",},
        ),
        migrations.AddField(
            model_name="master",
            name="UserRole",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="house_app.userrole"
            ),
        ),
    ]
